[package]
name = "xswezan/froute"
description = "A Router for Fusion 0.3"
version = "1.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Fusion = "elttob/fusion@0.3.0"